import { AddNameController } from './addNameController';

export interface AddNameScope extends ng.IScope
{
	list: Array<string>;
	an: AddNameController; // Generated by the controllerAs
}

export class AddNameDirective implements ng.IDirective
{
	public restrict = 'E';
	public templateUrl = 'addName.html';
	public scope = { list: '=' };
	public controller: 'AddNameController';
	public controllerAs: 'an';

	public static factory(): ng.IDirectiveFactory
	{
		const directive = () =>
		{
			return new AddNameDirective();
		};

		directive.$inject = [ '$timeout' ];

		return directive;
	}

	constructor() {}

	public link(scope: AddNameScope, element: ng.IAugmentedJQuery, attrs: ng.IAttributes, ctrl: AddNameController)
	{
		// Don't do anything yet
	}
}
